# Generated by Django 2.2.7 on 2019-11-28 23:20

import NaveAPI.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to=NaveAPI.models.user_file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=6000)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaveAPI.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=4000)),
                ('salary', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
                ('userADMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaveAPI.UserAdministrator')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
                ('jobVacancyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaveAPI.JobVacancy')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaveAPI.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='userADMID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaveAPI.UserAdministrator'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaveAPI.JobApplication'),
        ),
    ]
