# Generated by Django 2.2.7 on 2019-11-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaveAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='useradministrator',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='useradministrator',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
